### ISSUE TITLE
“more than one copy of React” error when running locally

### ISSUE THREAD

**Issue by rijk** [breadadams/scroller-motion#2]
Hi, I am trying to clone this package to create some PRs. But when I run it (after building), I keep getting this Next JS error:

![](https://user-images.githubusercontent.com/159500/85012395-3d818b00-b163-11ea-9950-0d3d5862b9fc.png)

I've asked the question [on the Next forums](https://github.com/vercel/next.js/discussions/14315) as well, but maybe you know a way to work around this?

**Comment by breadadams** [comment]
@rijk I just ran into this on another project, the solution was the suggestion from the React docs at the bottom of this section: https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

> Assuming `myapp` and `mylib` are sibling folders, one possible fix is to run `npm link ../myapp/node_modules/react` from `mylib`. This should make the library use the application’s React copy.

I think that's how I resolved this error with scroller-motion too, just comment if it doesn't do the trick 👌

**Comment by rijk** [comment]
Amazing. I would have never thought of that, but it worked! 👏 Next time I'll remember to check the React docs, haha.

PRs incoming 👾
