### ISSUE TITLE
Will this be upgraded to the latest version of framer-motion?

### ISSUE THREAD

**Issue by tyler-gits-me** [breadadams/scroller-motion#37]
Cool looking package, I want to try it out. But it's not compatible with the latest version of framer. Wondering if dependencies will be upgraded? Apologies, this may not be appropriate for issues, but will be watching this package. I couldn't find any live demos, have any available? Great work!

**Comment by breadadams** [comment]
Thanks @tyler-gits-me, this should be resolved in v1.2.3. As for live demos you can see: https://scroller-motion.js.org/

I'm looking into updating the examples, if there's anything you think could help I'd love to hear your feedback.
