### ISSUE TITLE
Cannot use ids to scroll to specific element

### ISSUE THREAD

**Issue by redoxahmii** [breadadams/scroller-motion#40]
cannot use <a> tags to scroll to a specific part of the page.

**Comment by breadadams** [comment]
I think the _Hash anchor scroll_ in [the recipes](https://github.com/breadadams/scroller-motion#recipes) is what you're after.

**Comment by redoxahmii** [comment]
Thank you for guidance.

**Comment by redoxahmii** [comment]
> I think the _Hash anchor scroll_ in [the recipes](https://github.com/breadadams/scroller-motion#recipes) is what you're after.

And using this method you cannot use Scale inside the ScrollerMotion anymore because it will not reach the element then. Should try to make it a part of the package rather than keeping it inside recipes. Currently i am multiplying and changing the value of offsetTop to make it work to some extent.
