### ISSUE TITLE
Flickering in Chrome when overscrolling

### ISSUE THREAD

**Issue by rijk** [breadadams/scroller-motion#7]
I was breaking my head over this, had a project where the flickering was really bad but in the Storybook demos I didn't see it at all. While comparing the code and CSS, I found this rule:

![image](https://user-images.githubusercontent.com/159500/92468701-dc061100-f1d3-11ea-8a7e-16ebc37c3052.png)

Which ended up completely fixing the problem. 🙌

So, takeaways:

1. The Storybook demos are awesome :)
2. Could the overscroll issues be fixed in the code maybe? Not sure what's causing them, but would be nice to not run into this.
3. If not: I think the need for `overscroll-behavior: none;` on `html` and `body` should be documented in the readme to save other people some time.

**Comment by breadadams** [comment]
In response to your comments:

1. Thanks! 😻 
2. We _could_, applying the style to the DOM internally or providing a util/hook for users. However something leans me towards having this in the docs to keep the bundle size down.
3. Yep, this is the way to go I think 👍

**Comment by MrUltimate** [comment]
Hey folks! Seems like this isn't something the Safari supports. Is there are recommended workaround for Safari specifically?
